### ISSUE TITLE
Ui/Ux Fixes

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#1078]
- [ ]  Swap Page: - Margin top seems to be 17px, let's change this to 8px. This way you don't have to scroll to see the full button.

- [ ]  Community banner in settings has a bit of empty space on the left side. 3px or so. Nitpicky but it looks off

_________

- [ ] Asset Card: - The hover effect doesn't change the Send icon colour, thus making it hard to see

- [ ] Send button should be clickable

<img width="366" alt="image" src="https://user-images.githubusercontent.com/80846886/156596380-07818eab-14c9-4f40-b9bf-65a9c9de0b18.png">

<img width="391" alt="image" src="https://user-images.githubusercontent.com/80846886/156596695-1c93e9d8-d4ce-4c43-b099-1b092d582161.png">

https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=7301%3A178747

**Comment by beemeeupnow** [comment]
I'll create a new issue if you want, but I figured this goes with the theme here.

Now that the Ledger item is shown, the alignment needs work so that the 'Create new wallet' item isn't cut off at the bottom:
![add_screen_needs_adjustment](https://user-images.githubusercontent.com/95515141/156701940-dfcdb3b7-d817-42a3-afbd-8c1b206a9536.png)

You can scroll, but there's no visible scroll bar and unless more options will be added I think the current ones can fit.

**Comment by VladUXUI** [comment]
Thanks for bringing it up @beemeeupnow . I didn't add this in because Henry is working on the new version for this page.

![image](https://user-images.githubusercontent.com/80846886/156712832-acaab992-01c2-48d2-bdcf-f9041e75a059.png)

**Comment by beemeeupnow** [comment]
looks slick, thank you for the info
 
missing a 't' in that pic :smile:
