### ISSUE TITLE
Update default Ledger derivation path 

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1105]
--> -m/44'/60'/0'/0,

**Comment by Shadowfiend** [comment]
Explanations/context in issues please!

We have #1102 which adds this derivation path, but the description there implies this is an old default rather than a correct current default. Are we sure we want it to be our default?

**Comment by fernya** [comment]
I think this is the current default, but MM uses an additional /0, which is not supported by us:
```
const LEDGER_LIVE_PATH = `m/44'/60'/0'/0/0`
```

**Comment by Shadowfiend** [comment]
Reference for derivation paths btw -> https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

What @cairomassimo was noting is that a good way to represent these is with an `x` or `*` in the path component that will be incremented to generate a new address. Ledger Live, i.e. most newer Ledgers, use `m/44'/60'/x'/0/0`, thus the additional Metamask 0. We don't present that in our UI, which is either correct or not depending on how you want to approach heh.

The legacy path seems to be `m/44'/60'/0'/x`, i.e. there is a level missing and it may derive at the end rather than at the hardened account level. It's not immediately clear if Metamask and other wallets derive at the end or at the account level, which we should also poke at.

**Comment by fernya** [comment]
MM and Ledger Live generated addresses match, they use the same `m/44'/60'/x'/0/0` base path to derive then increment.

The solution I added works with the legacy path too (adding the counter to the end of the path).

**Comment by cairomassimo** [comment]
Ok, IIRC the currently implemented scheme is `m/44'/60'/0'/0/x`, which gives different results except from the first address.
