### ISSUE TITLE
Add option to completely log out, also not able to read

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1152]
### Discord Discussion Link

n/a

### What would you like to be able to do?

Several users have requested that they'd like to be able to completely log out so that others can not see the wallet balances and activity.

I think ideally a user can set if

- He wants the auto lock feature to go to read-only or to not read at all
- Have the auto lock timer adjustable (issue #1151 )
- Have an option to manually log-out completely --> not read at all

**Comment by Shadowfiend** [comment]
A "manual log out" doesn't log anything out further than the existing lock--data is still fully available and unencrypted. Our position has generally been that this is a false sense of security. The password is most correctly thought of like a Ledger PIN rather than an app password. We've talked about adding balance hiding though (similar to Ledger Live).

Either way, I believe this is a duplicate of #989 or vice versa!

**Comment by Naxsun** [comment]
Yeah it's mostly a privacy feature for balance hiding. Missed the existing issue. Will close this one.
