### ISSUE TITLE
Add ETH balance for gas check & indicators 

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1432]
### Problem

Users getting 'dropped' transactions because they have no warning for not enough balance to cover gas fees, and they are allowed to continue anyway.

### Solution

Show a notification that balance is insufficient and disable next step

__________________

- [ ] **Sign Tx screens** 
- Disable sign button - If not enough funds to pay for baseFee
- Show notification if balance is insufficient for selected MaxGas

--

- [ ] **Gas control**
- Show notification if balance is insufficient for MaxGas

_____________

### Design
[Figma link](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/?node-id=9410%3A196066)

![image](https://user-images.githubusercontent.com/71384922/168030680-7c82f8ba-786e-440a-aa0a-5de2d4772f24.png)

**Comment by jagodarybacka** [comment]
Product decision already made - we display a warning only on tx approval screen

@puppycodes Blocked because of pending product decisions:
- what we should do with "max" button for base assets on Swap and Send asset pages. We don't know the gas fee estimate there yet (we know it on the tx approval screen). A possible solution for Send page would be to set a hardcoded gas limit as we know the minimum gas limit for the network.
- should we block the approve button or are we ok with the warning only? (gas price is an estimate, there is a possibility that the funds will be ok to cover the transaction despite the warning)

**Comment by jagodarybacka** [comment]
The description has been edited so it contains current requirements, no longer blocked
