### ISSUE TITLE
Persist activeNetwork in preference service.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1532]
We need to persist the [activeNetwork](https://github.com/tallycash/extension/blob/main/background/services/internal-ethereum-provider/index.ts#L117) in preference service to avoid mismatches between redux state (which persists the selected chain) and application state (which currently does not) on browser restart / app update.

**Comment by Shadowfiend** [comment]
Can't we just push the redux info from `Main` on `startService`?

**Comment by greg-nagy** [comment]
I think we can and probably we should.

When I started persisting settings in the preferences service I had the mental model that services should not depend on redux data, because redux is a kind of persistence layer for the UI. So it was ok for redux to depend on service but not the other way around.

But since then thinking of redux more like a UI/app settings service — so it can be queried and also can call other services — feels more natural. (And jumping the hops of keeping the 2 data persistence layer in sync through event hops is annoying an error-prone tbh)

What do you think?
