### ISSUE TITLE
Unable to use wallet with Decentraland

### ISSUE THREAD

**Issue by beemeeupnow** [tallycash/extension#1568]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/981572878690578483

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

* Go to https://play.decentraland.org/
* Select "Play using your wallet"
* Select "MetaMask"
* Tally Ho will pop up (when default and if you haven't already approved reading accounts here)

### What did not work?

* The page shows an error: `Invalid JSON RPC response: {"id":"","jsonrpc":"2.0","result":"1"}`

The method in the request is `net_version`.

I tried to see if the issue was on our side or theirs. It seems we send the right information, but would like confirmation that I didn't miss something.

### Version

Community Edition v0.13.7

**Comment by 0xDaedalus** [comment]
Yeah so the weird thing about this one is the message that they display to us does not match what we send them.  Specifically we send them `{"id":"1","jsonrpc":"2.0","result":"1"}` but do not reflect the id in their error message.

The [documentation for net_version](https://eth.wiki/json-rpc/API#net_version) suggests that we are sending back the correct response.  I wonder if the problem is on their side somewhere?

**Comment by Huzaifa181** [comment]
I am supposing that we are injecting TallyhoWindowProvider rather than injecting MetaMaskProvider, this override the "isMetaMask" property to false. so I am assuming that play.decentraland.org check this property as to enter in the game, I believe

**Comment by Huzaifa181** [comment]
Ya, need to contact with them

**Comment by Shadowfiend** [comment]
It looks like this is working now!
