### ISSUE TITLE
Overview page dosen't update after removing an account

### ISSUE THREAD

**Issue by mistricky** [tallycash/extension#1664]
### Discord Discussion Link

no

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

1. I have imported a wallet with no money
2. I have imported a wallet with some money, and I saw the balance of the overview page was updated correctly
3. Remove the second wallet which has some money
4. The balance of the overview page does not update

### What did not work?

Current: the balance of the overview page is $1, but I actually removed the second wallet
Expect: the balance of the overview page should update to $0

### Version

Community Edition v0.13.11

**Comment by jagodarybacka** [comment]
Took a look at this yesterday and it seems like the overview page is updating but sometimes it takes too much time and there is no loading indicator so it looks bugged. Definitely, we can improve it.

**Comment by henryboldi** [comment]
> Took a look at this yesterday and it seems like the overview page is updating but sometimes it takes too much time and there is no loading indicator so it looks bugged. Definitely, we can improve it.

The reason why the overview tab updates late is because `combinedData` is only updated via `updateAccountBalance()`. The wallet tab uses `accountsData` and _is_ updated by `deleteAccount()`.  `combinedData` should be factored out and replaced with a selector.

That said, a quick fix would be to have `deleteAccount` also update `combinedData`
