### ISSUE TITLE
Polygon | Polygon POS - Not able to bridge Ethereum to Polygon

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1745]
### **Build Info/PR/Commit:**
https://github.com/tallycash/extension/tree/polygon-qa-2

### **Reproduction Steps:**

1. nav to https://wallet.polygon.technology/
2. attempt to bridge ETH on Ethereum to Polygon

### **Expected Result:**
Success

### **Actual Result:**

![image](https://user-images.githubusercontent.com/103908695/177625675-35d5f374-f519-4741-97a8-c545a5af079f.png)

I also found this interesting.. is this the problem? Are we sending the price incorrectly?
![image](https://user-images.githubusercontent.com/103908695/177626093-23b6f63f-d492-485c-9382-f442334e391c.png)

**Comment by 0xDaedalus** [comment]
For your latter question - we are not ever actually sending price - just units of ether.  It is reasonable that our estimation of ether price and a given dapp's estimation of ether price might be a bit off due to rounding errors or simply due to the fact that we might be using a different source for the price than the dapp does

**Comment by 0xDaedalus** [comment]
@SJQuality would you mind re-checking this one?  I believe issues are resolved

**Comment by SJQuality** [comment]
Indeed!
