### ISSUE TITLE
Polygon | OpenSea - can not purchase NFT on Polygon network

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1752]
### **Reproduction Steps:**

1. https://opensea.io/
2. click "Explore" then "All NFTs"
3. Set "Chains" to "Polygon"
4. Find a NFT (sort by price lowest to highest)
5. attempt to purchase

### **Expected Result:**
Success! 

### **Actual Result:**

Failed
![image](https://user-images.githubusercontent.com/103908695/177641382-e430f84b-1086-43f8-bc61-8370133a39a1.png)

Same steps for Ethereum chain works fine.

**Comment by 0xDaedalus** [comment]
It seems that the [FuManChu](https://opensea.io/collection/fumanchu) collection this NFT belongs to has some issues with it.  The price is 0, and it has [never had a successful trade on opensea](https://opensea.io/collection/fumanchu/activity).  

Sorting low-to-high is a bit of a tough barometer because there are plenty of junk project on opensea (like the one above).  One thing you can do is ensure that buying an nft works in metamask - and then see if it also works in Tally (cause plenty don't work in metamaskl).

If you'd like a suggestion of a collection to test again - here's one that I found by sorting price low => high and filtering for NFTs above $2.

https://opensea.io/collection/hanumaan

**Comment by SJQuality** [comment]
Hmm.. tried one of those.. 
![image](https://user-images.githubusercontent.com/103908695/177857780-c6f66f97-eea4-4e16-9087-ab41790e6b20.png)
