### ISSUE TITLE
Personal Message Signing is broken on Ledger

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1971]
Steps to reproduce
- [ ] Clear chrome data (cookies, etc.) for opensea.io
- [ ] Import a ledger to tally, open ethereum app on ledger
- [ ] Navigate to opensea.io
- [ ] Connect with Tally
- [ ] Attempt to sign the ToS

<img width="614" alt="image" src="https://user-images.githubusercontent.com/94649004/185180639-38ee9441-5ad0-4841-bccf-ecc4ead570a5.png">

<img width="381" alt="image" src="https://user-images.githubusercontent.com/94649004/185181058-0f8a3607-8798-494a-a461-c4332cfab4b9.png">

After clicking `Sign` in the extension popup - the popup closes and no prompt to sign is displayed on the ledger.  There is a rather opaque error of `logger.ts:165 Async thunk failed TypeError: Cannot read properties of undefined (reading '0')` in the `background.js` logs with a stack trace that is unfortunately entirely inside of `node_modules` dependencies.

**Comment by Shadowfiend** [comment]
This was introduced in #1935, and is due to a subtlety of `Buffer.from().toString("hex")`, which I swapped out with passing hex data directly [here](https://github.com/tallycash/extension/pull/1935/files#diff-d0160e0605cd68e51eb095dc53f58cf560700156c57950c543809aa00b0ffc92L530). `Buffer.toString("hex")` does not include the `0x` prefix, whereas our hex data does. The Ledger library can't handle that and blows up.
