### ISSUE TITLE
Can't connect to optimism etherscan.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#2016]
Tally Ho is not able to connect to Etherscan.

Example URL: 
https://optimistic.etherscan.io/token/0x4200000000000000000000000000000000000006#writeContract

To recreate - click this button: 
<img width="180" alt="image" src="https://user-images.githubusercontent.com/94649004/186531536-50fdeba5-f611-4653-9a58-13c57478834c.png">

Notice the errors about `net_version` in the etherscan console.

**Comment by Shadowfiend** [comment]
Yeah, the issue here is we don't return a response for `net_version` unless the user has approved at least one account. We already respond to `eth_chainId` in these cases, I think we can except `net_version` as well. I'll handle this today, it's been a bugaboo of mine in the past and I've just never gotten it done heh.
