### ISSUE TITLE
Disable the "default wallet" setting by default for all wallets

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#2026]
It's a huge user complaint and a clear source of churn.

The behavior we want

- [ ] Prior onboarding, the wallet shouldn't act as if "default wallet" is set
- [ ] In the onboarding flow, the setting should default to "off"

**Comment by Shadowfiend** [comment]
Would be nice if we had a way of reprompting the user in upgrade rather than switching it off. 

Also feels somewhat at odds with #1918, maybe? Should we drop that with this change?

**Comment by VladUXUI** [comment]
I think the switch wallets feature in connect pages is still good. because you might enable Tally but still want to use Metamask or other wallets.
The downside of starting with "default off" is that users might have a hard time knowing how to turn it on. So this might be worth a bit of exploring.
I think we need to embrace the "multiple-extension" environment that we find ourselves in. This is backed by the survey, as many people use more wallets for different purposes.
Maybe having a toggle on and off at a more convenient place would help, i think it's worth exploring some options/solution to this. So instead of "pick me, pick me!" we go "pick me when you want/need"

**Comment by jagodarybacka** [comment]
As https://github.com/tallycash/extension/pull/1918 is still not published I think we should wait to see how users will react to that feature first. I think most annoying thing is when the wallet you didn't expected pop up during tx signing - and this feature is an answer for this. One thing that we should do before publishing is to test it with less popular wallets as this was mostly tested with MM.

**Comment by Shadowfiend** [comment]
> I think we need to embrace the "multiple-extension" environment that we find ourselves in. This is backed by the survey, as many people use more wallets for different purposes.

This feels fair. I do wonder if different wallets have different accounts (which 1918 solves and makes Tally an extension you might *want* as your default since it doesn't hog the default setting), but also appreciate that we're trying to experiment quickly here to avoid pushing people away before they've had a chance to get to know the wallet. 

Sounds good, thanks for walking through it @VladUXUI !

**Comment by VladUXUI** [comment]
Been thinking about this a bit more, and i think we run the risk of going to hard on the other side, if people don't know how to disable Tally as default, they won't know how to enable it as default. So i propose we add this bar for when Tally is disabled.
It's safe to assume that if it's disabled people don't actively use it for transactions or maybe don't even do too much in it. So it shouldn't be too much of a user friction to have the bar there.

If enabled, the bar should disappear in 10 seconds or so. Giving user a bit of time to disable back

<img width="2108" alt="image" src="https://user-images.githubusercontent.com/80846886/187387635-d8897302-cebc-4bca-ac0d-17a6e29db25c.png">

What do you all think?

**Comment by mhluongo** [comment]
I'm going to implement the first part of this (TH shouldn't be the default if it hasn't been onboarded yet) as I can't see any upside there at all — it just throws an error / gives a bad user experience. Waiting on the second checkbox while we get product / UX consensus.
