### ISSUE TITLE
Make broader user of `makeFetchWithTimeout`.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#2036]
We introduced [makeFetchWithTimeout](https://github.com/tallycash/extension/blob/main/background/services/name/resolvers/uns.ts#L8:L8) as part of a hotfix in `v0.14.6` to alleviate issues resulting from long http response times when querying UNS servers.  

We should extend and standardize this functionality to all `fetch` requests we make in the app with a default timeout (open to suggestions on what it should be) that is also configurable in case we need a shorter or longer timeout for a particular http endpoint.

**Comment by mhluongo** [comment]
I hate to be the bearer of bad news, but `setTimeout` and `setInterval` [don't work in Manifest v3](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/)... which we'll need to implement before EOY. That's why a lot of our backoff stuff is dumb / non-existent now — @Shadowfiend and I have discussed how we basically need a queuing framework that's v3-compatible to handle a bunch of retry logic that's table-stakes in other projects.

This might still be a good immediate idea, but the code will have to churn soon.

**Comment by Shadowfiend** [comment]
To be pedantic here, setTimeout and interval do work, but cannot be relied on. That is, the extension background script can be preempted by the browser and killed, at which point extant timers and intervals will not be resurrected when the extension is next fired up.

**Comment by mhluongo** [comment]
Good point! There might be some cases where that's okay... maybe for `fetch` timeouts and backoffs that's an acceptable tradeoff? If we go that route it needs to be heavily documented, I'd be really surprised as as future dev.
