### ISSUE TITLE
Prevent "thundering herd" UNS lookups by the `EnrichmentService`

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#2063]
![Screenshot from 2022-08-29 14-00-16](https://user-images.githubusercontent.com/427505/187267777-d807394a-1f49-4948-8c0a-79c85dc54260.png)

This is a mess :) and appears to be breaking all sorts of things. I believe fixing this without losing functionality is going to require an `EnrichmentService` refactor into phased enrichment.

**Comment by Shadowfiend** [comment]
We could probably improve some of this by using ethers `fetchJson` and adding a really dumb promise queue for the UNS resolver (where every new request checks if there is an existing lookup, and if so chains the current one with a promise `then` so that it runs after the previous lookup finishes). The ethers function handles backoff for 429s, the promise chain ensures we don't pile all the way on, and the main cost will be a complete loss of parallelism for UNS lookups. My instinct says layering the current timeout on top will lead to behavior that's similar to what we currently have but with higher overall likelihood of success. I could also be wrong 😅

**Comment by 0xDaedalus** [comment]
Can someone provide color on why we are concating all log `to` and `from` addresses here? https://github.com/tallycash/extension/blob/main/background/services/enrichment/transactions.ts#L62:L69

This is largely what is responsible for the huge amount of lookups

**Comment by Shadowfiend** [comment]
As opposed to doing what? This lets us resolve senders and recipients for token transfers to known names (when possible).

**Comment by 0xDaedalus** [comment]
I think we might need to tweak or rethink something here.

Take this transaction that sent an ERC-20 token to our test wallet for example: https://etherscan.io/tx/0x6131ade06b64a1316aea047b2f56c3ecf74c22048d7991bbb1c0524628ba7136

400 Transfers, so thats 800 enrichments, 799 of which we do not need.  I'd argue that this is something we should avoid regardless if the user is viewing the transaction in question in the UI or not.

**Comment by 0xDaedalus** [comment]
Another example of a tx with ~3.8k recipient / sender pairs that we are attempting to annotate: https://etherscan.io/tx/0x3c712768212cc75eec5329c6d08ed4a4edc679ee5c4553c6433c7b16259816fb
