### ISSUE TITLE
Periodically log `IndexedDB` and extension storage size

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#216]
We don't have a direction on telemetry longer-term yet, and we certainly don't have performance metrics to track in CI... but in the meantime a good consistent reminder of the storage space we're using will help build intuition during initial development.

H/t @itsrachelfish for making sure this stays on our radar.

**Comment by Shadowfiend** [comment]
Let's do this on `debug` level for now.

**Comment by itsrachelfish** [comment]
@Shadowfiend the logger library does not support the `debug` level.

Currently `logger.log()`, `logger.info()`, `logger.warn()`, and `logger.error()` all map to `console.log()`.

This was done because we wanted to include stack traces in every log message, and potentially store them in the future so users could submit bug reports. However `console.error()` always gets a stack trace added by the browser, meaning when we used `logger.error()` we would see two stack traces.

Perhaps we could switch the logger back to using the native console functions, and add a conditional check to not output our custom stack trace when using `logger.error()`? :thinking:

**Comment by Shadowfiend** [comment]
That sounds good to me!
