### ISSUE TITLE
Spike - inject Tally option into web3-react modal 

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#2437]
If user has Tally Ho installed, inject 'Tally option' into web3-react modal

**Comment by 0xDaedalus** [comment]
Closing this issue as the spike is complete - and the results of the spike can be seen in #2460.

It seems that it is prohibitively difficult to create a `one-size-fits-all` solution for injecting Tally into apps that use `web3-react` because of how barebones and DOM-agnostic `web3-react` is.  

We may have better luck with a more standardized library such as web3-onboard or rainbowkit - but those will need to be addressed in a separate spike.
