### ISSUE TITLE
User balances slow to update

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#2606]
User balances appear slow to update after a variety of actions are taken (bridge, swap, send, receive, etc.) that impact balance

Examples:

https://discord.com/channels/808358975287722045/888500174685614090/1040934220710826074
https://discord.com/channels/808358975287722045/888500174685614090/1040894186553102346
https://discord.com/channels/808358975287722045/888500174685614090/1040881421557964912
https://discord.com/channels/808358975287722045/888500174685614090/1040849194585444473
https://discord.com/channels/808358975287722045/888500174685614090/1040813236733349948
https://discord.com/channels/808358975287722045/888500174685614090/1040840667452145714
https://discord.com/channels/808358975287722045/888500174685614090/1040857200840691753

**Comment by greg-nagy** [comment]
Merging #2485 

### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1032600715610308638

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

View balance

### What did not work?

User:
"Please add a refresh option to the wallet or set the UI to update the portfolio. All assets are old until we connect to a dapp. This image shows that I have weth in tally but the dapp says no amount of it. You don't have it. The problem is when I want to do an internal swap in the Tally wallet."

![image](https://user-images.githubusercontent.com/71384922/197483535-b1c3910e-9d17-497c-bc07-d3ad5b76b023.png)

![image](https://user-images.githubusercontent.com/71384922/197483550-1a5a948a-d6a1-4bb1-bef4-de55c46ee139.png)

Logs:
[logs_v0_17_3__2022-10-20T14_08_2803_00 (1).txt](https://github.com/tallycash/extension/files/9850109/logs_v0_17_3__2022-10-20T14_08_2803_00.1.txt)



### Version

v0.17.3

### Relevant log output

_No response_

**Comment by Naxsun** [comment]
I don't know if this is new info or old info. 

But a significant portion of the cases involves bridging, where the bridged asset shows up on the new network, but also remains as balance on the previous network. 

E.g.
https://discord.com/channels/808358975287722045/888500174685614090/1041787272414117898

**Comment by chlolands** [comment]
[logs_v0_17_9__2022-11-14T16_55_07-05_00.txt](https://github.com/tallycash/extension/files/10007408/logs_v0_17_9__2022-11-14T16_55_07-05_00.txt)
From the following user: 0x7D220f11e35dca6a25c6d1c4706ab29976418887

Issue: Wallet is experiencing incorrect or slow balance display error

**Comment by Naxsun** [comment]
**User** dcnlk#6279
"More than 12 hours have passed. And I got very upset. Now my assets are not showing correctly. I changed inside the wbtc wallet and the interface shows that I have a lot of money, but it's not 😦
"

![image](https://user-images.githubusercontent.com/71384922/201920469-634daff7-bbc4-4239-b5b8-b19d7a59c75e.png)


https://discord.com/channels/808358975287722045/888500174685614090/1042047977432305664

[logs_v0_17_9__2022-11-15T15_14_4903_00.txt](https://github.com/tallycash/extension/files/10012657/logs_v0_17_9__2022-11-15T15_14_4903_00.txt)

**Comment by Naxsun** [comment]
Logs of a user with balance update issues after bridging. Asset is showing in both networks.

[logs_v0_17_9__2022-11-14T22_56_2202_00.txt](https://github.com/tallycash/extension/files/10018966/logs_v0_17_9__2022-11-14T22_56_2202_00.txt)
