### ISSUE TITLE
Warn before sending funds to a known ERC-20 contract

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#261]
This is a really easy safety win, and should be doable today without backend changes.

@VladUXUI this could happen sending ETH or ERC-20s. Ideas on how we might warn users off before they sign?

**Comment by Shadowfiend** [comment]
@mhluongo @VladUXUI this is probably increasingly easy at the sign stage with the newly-hooked-up enrichment service, _but_ not at the “send” stage.

Just to clarify the interaction here, if we wanted to look this up when sending ETH, we would have to block/put the page in a loading state until we could look up whether the address in question looked like a contract or not. Not sure if we like that friction, and we could reduce it by caching the last X addresses that were looked up, but we could never all the way get rid of the delay without risking the user hitting send before we can warn them.

**Comment by VladUXUI** [comment]
What waiting times are we talking about here @Shadowfiend?

**Comment by mhluongo** [comment]
Less than 250 ms on most network connections @VladUXUI. I think the approach would be to load the page, then have the "send" button be blocked rather than the whole page.

**Comment by VladUXUI** [comment]
Added to my to-do list

**Comment by mhluongo** [comment]
Background script changes for this landed in #1516. Should now be easy to snipe

**Comment by Shadowfiend** [comment]
Local state for the cache sounds reasonable. The functionality isn't completely implemented, I believe, but the framework for it is. 

Right now the warning that is implemented is for sending to the same token address that is being interacted with, where I believe this issue was also encompassing sending ETH to a contract address or any ERC20 to another ERC20 address. We can also probably start by only doing ERC20 contracts in our token lists before adding any extra lookup logic. 

I don't think the UI currently displays the send-to-token warning, so that's probably the biggest missing piece.

**Comment by mhluongo** [comment]
@hyphenized are you still interested in taking this? I'm doing some related background work, happy to advise if you want to take the frontend work!

Note the design from https://github.com/tallycash/extension/issues/525 might make more sense as it covers

> So we do need a "i know what i'm doing" function.

cc @VladUXUI

**Comment by mhluongo** [comment]
Closed by #1993
