### ISSUE TITLE
Transaction List

### ISSUE THREAD

**Issue by Shadowfiend** [tallycash/extension#368]

**Comment by henryboldi** [comment]
Temporarily for the community edition, how about we just include sent, received, and contract interactions (displaying one asset)? Contract interactions would cover swaps to avoid the impression that tokens were lost

**Comment by mhluongo** [comment]
Personally, I think that's great for a first release because we can do it accurately.

I think @Shadowfiend has something he's working on that goes a tiny bit further, recognizing ERC-20 transfers and approves. Whether we want to display those specially in the tx list or stick with the general contract interaction is unclear to me.

**Comment by henryboldi** [comment]
Handled by #538
