### ISSUE TITLE
Switching accounts in Tally doesn't get passed to Dapp

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#662]
Switching accounts doesn't seem to be registered by dapps.
Icould only test this with 1 import and 1 read me.

**Comment by VladUXUI** [comment]
Tested with two imported accounts, the switch still can't be made.
I switch accounts in Tally, but DApp is still seeing my other account.

**Comment by Shadowfiend** [comment]
Are we sure this behavior would be correct in the first place? Why should the dApp find out that I decided to look at my other account? What happens if I prefer to use account A in Alchemix and account B in Uniswap?

I realize that there's a piece of this that is “what other wallets do”, and that unless we support this behavior to some extent most dApps won't provide access to multiple addresses, but I'm wondering if the fundamental expectation is correct, and if we want to consider a better way, esp if one that places the decision-making in the user's hands in terms of switching accounts for a single dApp vs globally.

**Comment by VladUXUI** [comment]
First to answer the questions:
>Are we sure this behavior would be correct in the first place? 

We are not, it definitely deserves some exploration. 

> Why should the dApp find out that I decided to look at my other account?

It shouldn't, you should have control and let that dapp know that you want to use another account.

Ideally the automatic switch will happen only if both of your accounts are already connected. And you should have the ability to switch between account on a specific dapp. (This means introducing a switch account functionality)

Users need a close correlation between what is connected to a dapp and what they see in their wallet. And that is because most defi activities they do are based on what they have in their wallet.

Quick flow to help illustrate:
1 -  I first connect Account A to Uniswap (Account A shown in wallet as well)
2 - I connect Account B to Alchemix (Account B shown in wallet as well)
3 - I go back to Uniswap (Account B shown in wallet, but Uniswap is showing me account A)

This adds a bit of a stress factor and some cognitive load because you always feel the need to double check that the account you are seeing in your wallet is the account you are connected with, and thus you know what you can do or can't in that DApp. Otherwise you will try to do transactions that are going to fail because of your understanding of current possibilities within that account. Prevention is always better than errors


> What happens if I prefer to use account A in Alchemix and account B in Uniswap?

You would need to switch accounts in wallet. Users focus on one task at a time, so if they are on Uniswap they focus on that, and the wallet should reflect what they are currently interacting with if they open the wallet <this is an important !IF.
