### ISSUE TITLE
Not able to log into Uniswap on Firefox

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#665]
When I click connect wallet nothing happens

<img width="616" alt="Screen Shot 2021-12-15 at 12 52 12 PM" src="https://user-images.githubusercontent.com/7005061/146241809-dc9263b3-2446-45cf-bf7b-769cc19a9a59.png">

I'm able to connect to compound, balancer, yearn, and curve

**Comment by Shadowfiend** [comment]
Didn't realize this was FF specific but this is fixed by returning an empty array for `eth_accounts` if the wallet is not connected. I've patched it a few times locally since we weren't specifically targeting Uniswap for today.

It was unclear why this was a thing in the first place, even more puzzling if it's FF-specific.

**Comment by SJQuality** [comment]
I can't repro.. this is an old issue. Closing.
