### ISSUE TITLE
Properly display failed transactions

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#678]
As discovered testing a [recent PR](https://github.com/tallycash/extension/pull/673), we aren't showing failed transactions in activities! Here's what a failed tx currently looks like

![Screenshot from 2021-12-15 22-26-50](https://user-images.githubusercontent.com/427505/146303109-55aa5db5-18a8-430c-a7a3-6eac5414e932.png)

Instead, it should look... failed, and show the gas that was expended rather than the transaction value which didn't do anything.

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/146331828-81a4743e-6e6e-4383-bf70-cb89c7782168.png)

Has been designed previously, it might even be implemented in UI as far as i remember.
I think we should keep value because that is the first way people recognise a transaction.

Maybe remove To: or change what we display in TX details for Failed Transactions

**Comment by mhluongo** [comment]
Sniping this
