### ISSUE TITLE
Outgoing transaction is showing 'from' address instead of 'to' address

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#916]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/937417320047997050

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Check account activity.

### What did not work?

In the activity tab there is a 600 USDC outgoing transaction. This is showing the address where it's send from --> users wallet. This should display 'To' and the receiver address.

<img width="294" alt="Screen Shot 2022-01-30 at 19 29 24" src="https://user-images.githubusercontent.com/71384922/151712938-364639dc-7a4d-4064-9e67-1d81f5ddbcdf.png">

### Version

Community Edition v0.11.0

**Comment by Shadowfiend** [comment]
Right move here is to refactor this condition:

https://github.com/tallycash/extension/blob/d90ed07788abcfcec0b1f0a3f3776d84adf2d6e8/ui/components/Wallet/WalletActivityListItem.tsx#L149

If `isReceiveActivity` is `true`, we should use `senderAddress` rather than `fromTruncated`. So for send activities, use recipient address, for receive activities use the sender, and for all the rest use the from address. The former two are resolved in enrichment for asset transfers based on contract data, while the last one is the transaction originator.

**Comment by Shadowfiend** [comment]
On closer though, it's also possible we're misresolving the enrichment here 🤔
